### ISSUE TITLE
Is this working with VLC 3.17.4? 

### ISSUE THREAD

**Issue by lkblkb** [Daniel-Mendes/vlc-web-interface#1]
Hi, thanks for developing this. I tried it with a recent version of VLC but it didn't seem to be working with either Chrome or Firefox on Android (didn't try other browsers). A UI shows up but there are no controls, just the cover art and some un-marked sliders.

**Comment by Daniel-Mendes** [comment]
If your audio file as no title nor author name in metadata's, it will display just a dot.

I tried on android with chrome and v3.17.4 and you can click on the bottom audio tool and it will open controls in full screen.
